name: Gerar Dataset C Sintético

on:
  workflow_dispatch:  # Permite executar manualmente
  push:
    paths:
      - gerar_dataset.py
      - .github/workflows/gerar_dataset.yml

jobs:
  gerar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Executar script gerar_dataset.py
      run: python gerar_dataset.py

    - name: Upload como artifact
      uses: actions/upload-artifact@v4
      with:
        name: synthetic_c_dataset
        path: synthetic_c_dataset/

    - name: Commit e push dos arquivos gerados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add synthetic_c_dataset/
        git commit -m "Add dataset gerado automaticamente pelo GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin main
